ervices:
    ui:
      build: ./app
      ports:
        - 8080:8080
      volumes:
        - ./app:/app

      environment:
        - MODEL=llama3
        - EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
        - TARGET_SOURCE_CHUNKS=5

volumes:
  index_data:

networks:
  net:
